image: rocker/tidyverse

stages:
  - build
  - deploy

build:
    stage: build
    script:
        - R -e "remotes::install_deps(dependencies = TRUE)"
        - R -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', quiet = TRUE)"
    artifacts:
        paths:
            - public

# - R -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

deploy:
    image: node:latest
    stage: deploy
    before_script:
        - npm i -g netlify-cli
    script:
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    dependencies:
        - build
