project:
  type: r3-theme
  pre-render: bash _build-slides.sh
  resources:
    - videos/*
    - includes/cheatsheet.pdf
    - slides/*.html

book:
  title: "Reproducible Research in R"
  subtitle: "An introductory workshop on modern data analyses and workflows"
  description: "A 3-day workshop for researchers introducing modern and reproducible data analysis tools and workflows with R."
  author:
    - Luke W. Johnston
    - Helene Baek Juel
    - Bettina Lengger
    - Daniel R. Witte
    - Hannah Chatwin
    - Malene Revsbech Christiansen
    - Anders Aasted Isaksen
  site-url: "https://r-cubed-intro.rostools.org"
  repo-url: "https://github.com/rostools/r-cubed-intro"
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/syllabus.qmd
      - preamble/schedule.qmd
      - preamble/pre-course.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/project-management.qmd
      - sessions/version-control.qmd
      - sessions/data-management.qmd
      - sessions/reproducible-documents.qmd
      - sessions/data-visualization.qmd
      - sessions/what-next.qmd
  appendices:
    - appendix/social.qmd
    - appendix/assignment.qmd
    - appendix/for-instructors.qmd
    - appendix/extra-exercises.qmd
    - appendix/extra-github.qmd
    - appendix/extra-markdown.qmd
    - appendix/references.qmd
    - LICENSE.md
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html
      - text: "Code of Conduct"
        href: "https://guides.rostools.org/conduct.html"

bibliography:
  - includes/references.bib
  - includes/packages.bib

editor_options:
  markdown:
    wrap: 72
    canonical: true

format:
  r3-theme-html:
    include-before-body:
      - "includes/site-counter.html"
      - "includes/contribute.html"

execute:
  freeze: auto
  warning: false

