---
title: "instructing"
author: "olex2148"
editor: visual
---

 

## Data Visualization

```{r setup, warning=FALSE}
library(ggplot2)
library(tidyverse)
library(styler)

post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))

```

## Plot one continuous variable

```{r}

ggplot(post_meal_data, aes(x = BMI))
```

```{r bmi-histogram}

ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

```{r bmi-histogram}
#| fig-cap: "Distribution of BMI."
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

```

## Exercise: Plot a discrete variable

```{r solution-discrete-variables}
#| eval: false
#| code-fold: true
#| fig-cap: "Plot discrete, exercise"
#| label: fig-glykemi-bar
ggplot(post_meal_data, aes(x = glykemi)) +  geom_bar()

```

## Plot two discrete variables

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = glykemi)) +
  geom_bar()
```

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

If I wanted to remove the legend, which aspect of ggplot would I use,
recall, aes(), geom\_, scale\_, and theme\_?

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())

```

## Putting plots side by side

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

```{r}
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

```{r side-by-side-figs}
#| label: fig-bmi-glycemia
#| fig-cap: "BMI and glycemia, side by side."
#| fig-subcap:
#|   - "Distribution of BMI."
#|   - "Number of those with glycemia."
#| layout-ncol: 2
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()

```

## Make code readable, help yourself

```{r eval=FALSE}
# Object names
DayOne
T <- FALSE
c <- 9

# Spacing
x[,1]
x[ ,1]
mean (x, na.rm = TRUE)
mean( x, na.rm = TRUE )
height<-feet*12+inches
df $ z
x <- 1 : 10

# Tabs
if (x == 1) {
y <- 2
}

```

## Plotting two continuous variables

```{r}
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point()
```

```{r}
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()
```

```{r}
#| fig-cap: "Scatterplot of BMI and the area under the curve for glucose."
#| label: fig-bmi-auc-pg
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()
```
